### ISSUE TITLE
jekyll 3.1.1 | Error:  undefined method `to_liquid' for class `Jekyll::Post'

### ISSUE THREAD

**Issue by jaytxrx** [mpalmer/jekyll-static-comments#21] opened 2016-04-10 07:12 UTC
I am getting this error. I have placed the plugin inside the "_plugin" folder.

Could you please let me know how to fix this error ?

**Comment by binfalse** [comment] 2016-04-13 19:58
That's probably a duplicate of #20.

**Closed as completed** 2017-03-24 05:39 UTC
